spring:
  application:
    name: spring-boot-oauth2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.1.176:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: park

server:
  port: 8003

logging:
  level:
    org.springframework: info
